### ISSUE TITLE
comments welcome

### ISSUE THREAD

**Issue by yoyo1989** [metal-sn/SESNtemple#1]
I've done with this repository. Please have a look and list comments under this issue or open new issues. Once I've implemented the comments, I'll close issues. Thanks!

**Comment by fedhere** [comment]
@orgraur can you give us an outside look of the repo ane let us know if you have suggestions?

**Comment by orgraur** [comment]
@fedhere can you give me editing permissions? I've started proofreading, but it'll be easier if I can edit the README files directly.

**Comment by fedhere** [comment]
sure, we have several hands on those README already but i think it is just fine, since it is version controlled we can undo edits we dont like anyways :)

**Comment by fedhere** [comment]
Hi @orgraur, were you able to make changes after I changed the permissions? i do not see any commits from you.
