### ISSUE TITLE
AverageSpec: time sampling of "target/center phases"

### ISSUE THREAD

**Issue by mmoJazz** [metal-sn/SESNtemple#10]
I'm a bit confused why different types of SNe have different sampling of the "target/center phases" - I would think they should all have -10,-5,0,5,10,15,20,30,40, etc since
a) we say that we use target phase +/- 2 days around the center phase, so bins of 5 days
b) at later times (after ~20 days),  SNe doesn't change as much ( thus, we may consider using  "bigger bins", ie +/- 4 days, but that would be extra work, so perhaps not)

Currently,
IIb have -10,0,10,20 --> this is too sparse i think
Ib have -10,-5, 0, 10, 20, 30, 40, 50, 60, 65  --> why at 65?  and +5 is missing
Ic have -10, 0,10,20,30 -> missing: -5, 5, 15, 40 
Ic-bl have -10,-5, 0, 10, 15, 20, 30, but also in addition: 17, 32, 39 --> why was there a specific reason?
--> missing: 5, 40, 50

**Comment by mmoJazz** [comment]
ALong the same line: Once we're done with above, update README to include the phases at which we provide mean spec

**Comment by mmoJazz** [comment]
oops, i pressed "close" accidentally

**Comment by yoyo1989** [comment]
I just checked and actually we didn't show average spectra at +5 or -5 in our papers. I produce and plot some average spectra at +5 or -5 for exploration. I compared average spectrum of Ib at +65 to Ib-Ca 05E at +65 in my paper. For average spectra of Ic-bl Ic-bl at 17, 32, and 39, they are compared to other Ic-bl/Ic for other people, which are not shown in our papers. I put almost all average spectra I produce in this repository to provide users more choices.

**Comment by fedhere** [comment]
we should choose a cadence, eg 5 days, and produce mean spectra at all
those phases

On Mon, Jul 11, 2016 at 11:08 PM, Yuqian Liu notifications@github.com
wrote:

> I just checked and actually we didn't show average spectra at +5 or -5 in
> our papers. I produce and plot some average spectra at +5 or -5 for
> exploration. I compared average spectrum of Ib at +65 to Ib-Ca 05E at +65
> in my paper. For average spectra of Ic-bl Ic-bl at 17, 32, and 39, they are
> compared to other Ic-bl/Ic for other people, which are not shown in our
> papers. I put almost all average spectra I produce in this repository to
> provide users more choices.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nyusngroup/SESNtemple/issues/10#issuecomment-231925945,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABnkhq95En4G6_7QcIqJRylg5WhpqTm1ks5qUwUtgaJpZM4JJk7c
> .

## 

---

dr. federica bianco
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/

---

  //\
 //||\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.

**Comment by mmoJazz** [comment]
I agree with Fed. THanks!

**Comment by mmoJazz** [comment]
Also we say in our papers that we'll publish more mean spectra than shown in our plots. A cadence of 5 days is the minimum given our bin/window size is target phase +/- 2 days. We could consider producing every 10 days after e.g. 30 days, since the spectra don't change that much, but I don't think so. Releasing these mean spec with a cadence of 5 days will also obviate the need to release the more finely time-sampled mean spec that we constructed for the Ic template fitting method - so less confusion!

So let's say for all SNtypes: very 5 days starting at -10, up to 50days.

Ideally some time in the future, we or Stephane will release the code to produce mean spectra!

Thanks!

**Comment by yoyo1989** [comment]
I agree with you. I'll produce more average spectra and put them in repository.

**Comment by fedhere** [comment]
hi yuqian, please make sure the naming scheme is changed in your code
before you do:
everywhere use:
grb ->GRB
sn ->SN
bl->BL
then we used SNhlGRB and SNllGRB for cosmological and low luminosity
respectively

f

On Wed, Jul 13, 2016 at 12:34 AM, Yuqian Liu notifications@github.com
wrote:

> I agree with you. I'll produce more average spectra and put them in
> repository.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/nyusngroup/SESNtemple/issues/10#issuecomment-232254232,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABnkhn-T53PeBD_-QHKpGQAD7Wy15fCdks5qVGrcgaJpZM4JJk7c
> .

## 

 /|/\
   |\*  Please consider the environment before printing this e-mail

**Comment by yoyo1989** [comment]
done
