### ISSUE TITLE
the readme inside SNID templates need formatting

### ISSUE THREAD

**Issue by fedhere** [metal-sn/SESNtemple#2]
the readme files need extention to be rendered properly by github, so i added .md to the file name.

still there are formatting issues. please take a look and fix the formatting so that the reader can easily follow the logic

**Comment by yoyo1989** [comment]
I tried this before and found it's not easy to solve this formatting issue. I have to spend more time on this issue.

**Comment by mmoJazz** [comment]
Yuqian, it may be helpful to look at the syntax by markdown  - FEd sent me the link: 
https://guides.github.com/features/mastering-markdown/

esp the tables may be helpful

Actually in general I would suggest putting the info on 
Temp_name IAU_name Type Redshift MJD_Tmax Band Method Ref_spec
in an ASCII file in the directory and not be part of the README. The README should give a general overview here, but not be like the "bibliography"

**Comment by mmoJazz** [comment]
After talking with FEd, this is a 2-part issue (1) taking the tables from the README and turning them into csv files (which Fed will do) and 2) adding more text and context to README. So I'm closing this issue and opening 2 new ones with differently assigned people.
