### ISSUE TITLE
moving mean spectra for template fitting code to SNspectraLib directory

### ISSUE THREAD

**Issue by mmoJazz** [metal-sn/SESNtemple#4]
> ```
> Hi Yuqian
> 
> After talking with Fed (she and I are just meeting now), it appears
> that the mean spectra for the template fitting project should only be
> in the code repo, since those should only be used for the template
> fitting projects.
> ```
> 
> I don't think so. People can use these mean spectra for other purposes 
> such as detecting novel SNe.

Actually that's what the other mean spectra are for- the ones we display in our papers and which are independent (ie every 5 days) . I worry that we will confuse the user/reader if we have too many versions of the mean spectra (and we alreayd have a bunch) - I mean i have a hard time keeping track - that's why we have the google doc :>

So I still think that the mean spectra for the template fitting project should only live in the code repo.

**Comment by yoyo1989** [comment]
done
