### ISSUE TITLE
mean spectra that have been smoothed via FT method (ours) vs. band-pass (Stephane's)

### ISSUE THREAD

**Issue by mmoJazz** [metal-sn/SESNtemple#5]
> ```
> In this context, shall we modify the entry here by saying that the
> mean spectra have been all smoothed by our own FT method? 
> 
> I think
> that's what we decided at the end for def. my paper on the SNe Ic-bl
> and SNe Ic - def. also for the SLSN - what about for SNe IIb and Ib? 
> ```
> 
> I put both mean spectra smoothed by FFT and mean spectra smoothed by 
> band-pass filter in the repository. Yes, in Modjaz et al. (2016), 
> average spectra are smoothed by FFT, while in Liu et al. (2016), average 
> spectra are smoothed by band-pass filter.

I think we have too many different versions of the mean spectra, in general, and for the FT smoothed vs band-pass smoothed, in particular. I would say that the FT smoothed ones are more appropriate for SNe Ic-bl and SNe Ic (as we found, less high-frequency noise) and those are the ones we're showing in our paper - and those should be the only ones included here. 
So can you please remove the non-ft-smoothed ones for SNe Ic and SNe Ic-bl?

For SNe Ib & IIb (in your paper): while we never did a full comparison b/w the band-pass smoothed and the FT smoothed mean spectra, I see that for some phases you include the FT smoothed and for others you don't - is there is a specific reason? I think for clarity and from what we argue about the merits of FT smoothing, we should _only_ distribute FT-smoothed spectra (and it's only b/c of history that we have the bandpass filtered ones since those are the ones that go into the SNID library). 
I think providing both will just confuse the user/reader.

Also for clarity, for SNe Ic: in your paper, did you use the FT smoothed ones (which we did in my paper) or the bandpass filtered ones?

**Comment by yoyo1989** [comment]
I removed non-FFT smoothed Ic-bl average spectra. Since in Liu et al. (2016), I still use bandpass filtered ones, I presume we'll keep bandpass filtered non-Ic-bl average spectra, right? @mmoJazz

**Comment by mmoJazz** [comment]
Yes, only keep the mean spectra we actually used. For Ic; we ended up using FFT smoothed spectra in my paper, so also let's keep those too! @yoyo1989

**Comment by yoyo1989** [comment]
If we only keep the mean spectra we actually used, I have to remove average spectra of LLSN-GRB and HLSN-GRB, since they are not shown in your paper. I also have to remove average spectra of Ib and IIb that include all spectra per SN, since they are not shown in my paper. However, I do think the above spectra are valuable, thus I prefer to keep them and give users more choices.

**Comment by mmoJazz** [comment]
OK . 

For the mean spectra of SN with LLGRBs vs those of HLGRBs: we may want to have a note/disclaimer that the SNLLGRB mean spectra are dominated by the extreme 10bh which has very large width and absorption velocities, and given the small number statistics, such that the mean spectrum of SNLLGRB appears in general broader than those  of SNHLGRB  - but we don't think that that's statistically significant. Though while I'm writing this, I wonder whether we should, given it's such a detailed note...

**Comment by yoyo1989** [comment]
done
