### ISSUE TITLE
check and remove SNIDfiles .lnw in templates_new and templates_adjusted

### ISSUE THREAD

**Issue by mmoJazz** [metal-sn/SESNtemple#9]
From a cursive look at the content of  templates_new and templates_adjusted, I see that those SNe do not agree with those listed in the README file:  eg. 
08D is listed in both  templates_new and templates_adjusted, but it should just be in  templates_adjusted, 
10bh is listed in templates_adjusted, but shouldn't be there...

Please check all and correct. @yoyo1989

**Comment by yoyo1989** [comment]
yes, 08D should only in templates_adjusted, and 10bh should only be in templates_new. I've updated the number of SNe and spectra in the README file, and done the sanity check.
